### ISSUE TITLE
[question] how stable is transaction implementation?

### ISSUE THREAD

**Issue by mvayngrib** [aaaristo/dyngodb#19]
i realize this library isn't maintained anymore, but how stable/mature is the transaction support?

**Comment by aaaristo** [comment]
It is a way outdated. And it is an experiment.
It never left alpha stage.

**Comment by mvayngrib** [comment]
@aaaristo hey, thanks for getting back to me. Do you know of a more mature JS dynamodb transactions implementation?

**Comment by aaaristo** [comment]
Unfortunately not, but nowadays with babel and async/ await copying the
java one should be a breeze.

**Comment by mvayngrib** [comment]
@aaaristo i see, thanks. How significant was the performance drop? For example two puts in one transaction vs two puts in parallel?

**Comment by aaaristo** [comment]
As far as I recall, it was 7 writes more for each write. But it should be
better described in the dynamo-transactions java project. Still each block
of writes can happen in parallel.

Please refer to:
https://github.com/awslabs/dynamodb-transactions/blob/master/DESIGN.md

**Comment by mvayngrib** [comment]
@aaaristo awesome, thanks for the help!
